version: '3.8'
services:
  web:
    image: jackson147/wadebridge-gaming-group:0.23
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
    command: npm start