version: '3.8'
services:
  # web:
  #   image: wadebridge-gaming-group
  #   build:
  #     context: .
  #     args:
  #       - AUTH_URL=http://localhost:3000
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   env_file:
  #     - .env.compose
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgadmin-data:
  postgres-data: